#Pandas(29-05-2026)

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df={
    "name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
    "age":[25,np.nan,35,40,50,np.nan,43,45],
    "city":["New York","Los Angeles","Chicago","Houston","hongkong","delhi",np.nan,"kolkata"],
    "sal":[50000,60000,70000,80000,30000,32000,45000,870000],
    "Experience":[2,5,7,np.nan,15,1,8,np.nan],
    "Dept":["IT","HR","Finance",np.nan,"HR","Finance","IT","HR"]
    }
df=pd.DataFrame(df)
df

      name   age         city     sal  Experience     Dept
0    Rahul  25.0     New York   50000         2.0       IT
1      Joy   NaN  Los Angeles   60000         5.0       HR
2    Kumar  35.0      Chicago   70000         7.0  Finance
3     Mahi  40.0      Houston   80000         NaN      NaN
4   Jhanvi  50.0     hongkong   30000        15.0       HR
5  Shubham   NaN        delhi   32000         1.0  Finance
6    Priya  43.0          NaN   45000         8.0       IT
7     Anit  45.0      kolkata  870000         NaN       HR

In [ ]:
df.isna()
df.isnull() #displays true where data is missing

    name    age   city    sal  Experience   Dept
0  False  False  False  False       False  False
1  False   True  False  False       False  False
2  False  False  False  False       False  False
3  False  False  False  False        True   True
4  False  False  False  False       False  False
5  False   True  False  False       False  False
6  False  False   True  False       False  False
7  False  False  False  False        True  False

In [ ]:
df.notna() #Shows false where the data is missing
df.notna().sum() #it shows not null values

name          8
age           6
city          7
sal           8
Experience    6
Dept          7
dtype: int64

In [ ]:
df.notna().mean()*100

name          100.0
age            75.0
city           87.5
sal           100.0
Experience     75.0
Dept           87.5
dtype: float64

In [ ]:
df[df.isna().any(axis=1)] #displays the rows which contain even one empty element
df[df.isna().all(axis=1)] #to check the complete empty row

Empty DataFrame
Columns: [name, age, city, sal, Experience, Dept]
Index: []

In [ ]:
df[df["age"].isna()] #displays complete rows in which the specific col values are empty

      name  age         city    sal  Experience     Dept
1      Joy  NaN  Los Angeles  60000         5.0       HR
5  Shubham  NaN        delhi  32000         1.0  Finance

In [ ]:
df.dropna() #this function drops the rows or col from the dataset
df.dropna(subset=["age"]) #this drops the rows which have missing values in specific column
df

      name   age         city     sal  Experience     Dept
0    Rahul  25.0     New York   50000         2.0       IT
1      Joy   NaN  Los Angeles   60000         5.0       HR
2    Kumar  35.0      Chicago   70000         7.0  Finance
3     Mahi  40.0      Houston   80000         NaN      NaN
4   Jhanvi  50.0     hongkong   30000        15.0       HR
5  Shubham   NaN        delhi   32000         1.0  Finance
6    Priya  43.0          NaN   45000         8.0       IT
7     Anit  45.0      kolkata  870000         NaN       HR

In [ ]:
df={
    "name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
    "age":[25,np.nan,35,40,50,np.nan,43,45],
    "city":["New York","Los Angeles","Chicago","Houston","hongkong","delhi",np.nan,"kolkata"],
    "sal":[50000,60000,70000,80000,30000,32000,45000,870000],
    "Experience":[2,5,7,np.nan,15,1,8,np.nan],
    "Dept":["IT","HR","Finance",np.nan,"HR","Finance","IT","HR"]
    }
df=pd.DataFrame(df)
df

      name   age         city     sal  Experience     Dept
0    Rahul  25.0     New York   50000         2.0       IT
1      Joy   NaN  Los Angeles   60000         5.0       HR
2    Kumar  35.0      Chicago   70000         7.0  Finance
3     Mahi  40.0      Houston   80000         NaN      NaN
4   Jhanvi  50.0     hongkong   30000        15.0       HR
5  Shubham   NaN        delhi   32000         1.0  Finance
6    Priya  43.0          NaN   45000         8.0       IT
7     Anit  45.0      kolkata  870000         NaN       HR

In [ ]:
df.dropna(axis=1)#displays not null cols
df.dropna(axis=0)#displays not null rows

     name   age      city    sal  Experience     Dept
0   Rahul  25.0  New York  50000         2.0       IT
2   Kumar  35.0   Chicago  70000         7.0  Finance
4  Jhanvi  50.0  hongkong  30000        15.0       HR

In [ ]:
df["Experience"].fillna(0)
df["city"].fillna("Unknown")

0       New York
1    Los Angeles
2        Chicago
3        Houston
4       hongkong
5          delhi
6        Unknown
7        kolkata
Name: city, dtype: object

In [ ]:
df.fillna({"Experience":0,"city":"Unknown"})

      name   age         city     sal  Experience     Dept
0    Rahul  25.0     New York   50000         2.0       IT
1      Joy   NaN  Los Angeles   60000         5.0       HR
2    Kumar  35.0      Chicago   70000         7.0  Finance
3     Mahi  40.0      Houston   80000         0.0      NaN
4   Jhanvi  50.0     hongkong   30000        15.0       HR
5  Shubham   NaN        delhi   32000         1.0  Finance
6    Priya  43.0      Unknown   45000         8.0       IT
7     Anit  45.0      kolkata  870000         0.0       HR

###Filling the empty values statistically

In [ ]:
df["age"].fillna(df["age"].mean())
df["age"].fillna(df["age"].median())

0    25.0
1    41.5
2    35.0
3    40.0
4    50.0
5    41.5
6    43.0
7    45.0
Name: age, dtype: float64

In [ ]:
df["city"].fillna(df["city"].mode())
df["Dept"].fillna(df["Dept"].mode()[0])

0         IT
1         HR
2    Finance
3         HR
4         HR
5    Finance
6         IT
7         HR
Name: Dept, dtype: object

In [ ]:
df.replace("Finance","Fina")

      name   age         city     sal  Experience  Dept
0    Rahul  25.0     New York   50000         2.0    IT
1      Joy   NaN  Los Angeles   60000         5.0    HR
2    Kumar  35.0      Chicago   70000         7.0  Fina
3     Mahi  40.0      Houston   80000         NaN   NaN
4   Jhanvi  50.0     hongkong   30000        15.0    HR
5  Shubham   NaN        delhi   32000         1.0  Fina
6    Priya  43.0          NaN   45000         8.0    IT
7     Anit  45.0      kolkata  870000         NaN    HR

#TASK 1(29-05-2026)

In [ ]:
data={
    "Student":["Alice","Bob","Charlie","David","rohit","agastya","amar","joy"],
    "maths":[85,90,np.nan,92,88,95,80,91],
    "science":[80,85,90,np.nan,88,92,np.nan,89],
    "English":[75,80,85,90,88,92,84,89],
    "Sanskrit":[70,75,np.nan,85,88,90,82,87],
    "Attendance":[90,85,95,80,88,np.nan,84,89]
}
df=pd.DataFrame(data)
df

   Student  maths  science  English  Sanskrit  Attendance
0    Alice   85.0     80.0       75      70.0        90.0
1      Bob   90.0     85.0       80      75.0        85.0
2  Charlie    NaN     90.0       85       NaN        95.0
3    David   92.0      NaN       90      85.0        80.0
4    rohit   88.0     88.0       88      88.0        88.0
5  agastya   95.0     92.0       92      90.0         NaN
6     amar   80.0      NaN       84      82.0        84.0
7      joy   91.0     89.0       89      87.0        89.0

In [ ]:
df.isna().sum()

Student       0
maths         1
science       2
English       0
Sanskrit      1
Attendance    1
dtype: int64

In [ ]:
avg=df["maths"].sum()/df["maths"].count()
df["maths"].fillna(avg)

0    85.000000
1    90.000000
2    88.714286
3    92.000000
4    88.000000
5    95.000000
6    80.000000
7    91.000000
Name: maths, dtype: float64

In [ ]:
df["English"].fillna(0)

0    75
1    80
2    85
3    90
4    88
5    92
6    84
7    89
Name: English, dtype: int64

In [ ]:
df.isna()

   Student  maths  science  English  Sanskrit  Attendance
0    False  False    False    False     False       False
1    False  False    False    False     False       False
2    False  False    False    False     False       False
3    False  False    False    False     False       False
4    False  False    False    False     False       False
5    False  False    False    False     False       False
6    False  False    False    False     False       False
7    False  False    False    False     False       False

In [ ]:
avg=df["Attendance"].sum()/df["Attendance"].count()
df["Attendance"].fillna(avg)

0    90.000000
1    85.000000
2    95.000000
3    80.000000
4    88.000000
5    87.285714
6    84.000000
7    89.000000
Name: Attendance, dtype: float64

In [ ]:
df[df.isna().sum(axis=1)<=2]

   Student      maths    science  English   Sanskrit  Attendance
0    Alice  85.000000  80.000000       75  70.000000   90.000000
1      Bob  90.000000  85.000000       80  75.000000   85.000000
2  Charlie  88.714286  90.000000       85  82.428571   95.000000
3    David  92.000000  87.333333       90  85.000000   80.000000
4    rohit  88.000000  88.000000       88  88.000000   88.000000
5  agastya  95.000000  92.000000       92  90.000000   87.285714
6     amar  80.000000  87.333333       84  82.000000   84.000000
7      joy  91.000000  89.000000       89  87.000000   89.000000