#Data Cleaning

In [51]:
import pandas as pd
import numpy as np
from datetime import datetime

In [52]:
data = {
    "CustomerName": ["Rahul Sharma", "priya patel", "AMIT KUMAR", "neha gupta", "Vikas Jain", "priya patel", "sneha reddy", "rahul sharma ", "Pooja Mehta", None],
    "OrderDate": ["2023-01-01", "2023-01-01", "2023-01-02", "2023-01-02", "2023-01-03", "2023-01-03", "2023-01-04", "2023-01-04", "2023-01-05", None],
    "ProductName": ["Laptop", "Mouse", "Keyboard", "Monitor", "Laptop", "Webcam", "Headphones", "Mouse", "Keyboard", "Monitor"],
    "Quantity": ['1','2','1', '1', '-3', '1', '2', '1', '1', '1'],
    "Price": [1200, 25, 75, 250, 1150, 45, 150, 20, 80, 260],
    "City": ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Delhi", "Kolkata", "Mumbai", "Pune", "Ahmedabad"],
    "DeliveryDate": ["2023-01-05", "2023-01-03", "2023-01-06", "2023-01-07", "2023-01-08", "2023-01-05", "2023-01-07", "2023-01-06", "2023-01-09", "2023-01-08"]
}
df = pd.DataFrame(data)
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Rahul Sharma,2023-01-01,Laptop,1,1200,Mumbai,2023-01-05
1,priya patel,2023-01-01,Mouse,2,25,Delhi,2023-01-03
2,AMIT KUMAR,2023-01-02,Keyboard,1,75,Bangalore,2023-01-06
3,neha gupta,2023-01-02,Monitor,1,250,Hyderabad,2023-01-07
4,Vikas Jain,2023-01-03,Laptop,-3,1150,Chennai,2023-01-08
5,priya patel,2023-01-03,Webcam,1,45,Delhi,2023-01-05
6,sneha reddy,2023-01-04,Headphones,2,150,Kolkata,2023-01-07
7,rahul sharma,2023-01-04,Mouse,1,20,Mumbai,2023-01-06
8,Pooja Mehta,2023-01-05,Keyboard,1,80,Pune,2023-01-09
9,None,None,Monitor,1,260,Ahmedabad,2023-01-08

In [53]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   CustomerName  9 non-null      object
 1   OrderDate     9 non-null      object
 2   ProductName   10 non-null     object
 3   Quantity      10 non-null     object
 4   Price         10 non-null     int64
 5   City          10 non-null     object
 6   DeliveryDate  10 non-null     object
dtypes: int64(1), object(6)
memory usage: 692.0+ bytes

CustomerName    1
OrderDate       1
ProductName     0
Quantity        0
Price           0
City            0
DeliveryDate    0
dtype: int64

In [54]:
df.dtypes

CustomerName    object
OrderDate       object
ProductName     object
Quantity        object
Price            int64
City            object
DeliveryDate    object
dtype: object

In [55]:
df.duplicated().sum() # it displays duplicate rows

np.int64(0)

In [56]:
df["CustomerName"]=df["CustomerName"].str.strip()#this will remove leading and trailing spaces
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Rahul Sharma,2023-01-01,Laptop,1,1200,Mumbai,2023-01-05
1,priya patel,2023-01-01,Mouse,2,25,Delhi,2023-01-03
2,AMIT KUMAR,2023-01-02,Keyboard,1,75,Bangalore,2023-01-06
3,neha gupta,2023-01-02,Monitor,1,250,Hyderabad,2023-01-07
4,Vikas Jain,2023-01-03,Laptop,-3,1150,Chennai,2023-01-08
5,priya patel,2023-01-03,Webcam,1,45,Delhi,2023-01-05
6,sneha reddy,2023-01-04,Headphones,2,150,Kolkata,2023-01-07
7,rahul sharma,2023-01-04,Mouse,1,20,Mumbai,2023-01-06
8,Pooja Mehta,2023-01-05,Keyboard,1,80,Pune,2023-01-09
9,None,None,Monitor,1,260,Ahmedabad,2023-01-08

In [57]:
df["CustomerName"]=df["CustomerName"].str.strip()
df["CustomerName"]=df["CustomerName"].str.capitalize()#this convert the first letter into uppercase
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Rahul sharma,2023-01-01,Laptop,1,1200,Mumbai,2023-01-05
1,Priya patel,2023-01-01,Mouse,2,25,Delhi,2023-01-03
2,Amit kumar,2023-01-02,Keyboard,1,75,Bangalore,2023-01-06
3,Neha gupta,2023-01-02,Monitor,1,250,Hyderabad,2023-01-07
4,Vikas jain,2023-01-03,Laptop,-3,1150,Chennai,2023-01-08
5,Priya patel,2023-01-03,Webcam,1,45,Delhi,2023-01-05
6,Sneha reddy,2023-01-04,Headphones,2,150,Kolkata,2023-01-07
7,Rahul sharma,2023-01-04,Mouse,1,20,Mumbai,2023-01-06
8,Pooja mehta,2023-01-05,Keyboard,1,80,Pune,2023-01-09
9,None,None,Monitor,1,260,Ahmedabad,2023-01-08

In [58]:
df.dropna(inplace=True)
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Rahul sharma,2023-01-01,Laptop,1,1200,Mumbai,2023-01-05
1,Priya patel,2023-01-01,Mouse,2,25,Delhi,2023-01-03
2,Amit kumar,2023-01-02,Keyboard,1,75,Bangalore,2023-01-06
3,Neha gupta,2023-01-02,Monitor,1,250,Hyderabad,2023-01-07
4,Vikas jain,2023-01-03,Laptop,-3,1150,Chennai,2023-01-08
5,Priya patel,2023-01-03,Webcam,1,45,Delhi,2023-01-05
6,Sneha reddy,2023-01-04,Headphones,2,150,Kolkata,2023-01-07
7,Rahul sharma,2023-01-04,Mouse,1,20,Mumbai,2023-01-06
8,Pooja mehta,2023-01-05,Keyboard,1,80,Pune,2023-01-09

In [59]:
df["City"]=df["City"].replace({"Mumbai":"Goa","Chennai":"Madras"})
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Rahul sharma,2023-01-01,Laptop,1,1200,Goa,2023-01-05
1,Priya patel,2023-01-01,Mouse,2,25,Delhi,2023-01-03
2,Amit kumar,2023-01-02,Keyboard,1,75,Bangalore,2023-01-06
3,Neha gupta,2023-01-02,Monitor,1,250,Hyderabad,2023-01-07
4,Vikas jain,2023-01-03,Laptop,-3,1150,Madras,2023-01-08
5,Priya patel,2023-01-03,Webcam,1,45,Delhi,2023-01-05
6,Sneha reddy,2023-01-04,Headphones,2,150,Kolkata,2023-01-07
7,Rahul sharma,2023-01-04,Mouse,1,20,Goa,2023-01-06
8,Pooja mehta,2023-01-05,Keyboard,1,80,Pune,2023-01-09

In [60]:
def parseDate(datestr):
  if pd.isna(datestr):
    return pd.NaT
  datestr=str(datestr).strip()
  formats=['%Y-%m-%d','%Y/%m/%d','%d-%m-%Y','%Y-%d-%m','%d/%m/%Y']
  for fmt in formats:
    try:
      return pd.to_datetime(datestr,format=fmt)
    except:
      continue
  return pd.NaT
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Rahul sharma,2023-01-01,Laptop,1,1200,Goa,2023-01-05
1,Priya patel,2023-01-01,Mouse,2,25,Delhi,2023-01-03
2,Amit kumar,2023-01-02,Keyboard,1,75,Bangalore,2023-01-06
3,Neha gupta,2023-01-02,Monitor,1,250,Hyderabad,2023-01-07
4,Vikas jain,2023-01-03,Laptop,-3,1150,Madras,2023-01-08
5,Priya patel,2023-01-03,Webcam,1,45,Delhi,2023-01-05
6,Sneha reddy,2023-01-04,Headphones,2,150,Kolkata,2023-01-07
7,Rahul sharma,2023-01-04,Mouse,1,20,Goa,2023-01-06
8,Pooja mehta,2023-01-05,Keyboard,1,80,Pune,2023-01-09

In [61]:
df["OrderDate"]=df["OrderDate"].apply(parseDate)
df["DeliveryDate"]=df["DeliveryDate"].apply(parseDate)
df

   CustomerName  OrderDate ProductName Quantity  Price       City DeliveryDate
0  Rahul sharma 2023-01-01      Laptop        1   1200        Goa   2023-01-05
1   Priya patel 2023-01-01       Mouse        2     25      Delhi   2023-01-03
2    Amit kumar 2023-01-02    Keyboard        1     75  Bangalore   2023-01-06
3    Neha gupta 2023-01-02     Monitor        1    250  Hyderabad   2023-01-07
4    Vikas jain 2023-01-03      Laptop       -3   1150     Madras   2023-01-08
5   Priya patel 2023-01-03      Webcam        1     45      Delhi   2023-01-05
6   Sneha reddy 2023-01-04  Headphones        2    150    Kolkata   2023-01-07
7  Rahul sharma 2023-01-04       Mouse        1     20        Goa   2023-01-06
8   Pooja mehta 2023-01-05    Keyboard        1     80       Pune   2023-01-09

In [63]:
df["Quantity"]=df["Quantity"].astype("int64")
df.dtypes

CustomerName            object
OrderDate       datetime64[ns]
ProductName             object
Quantity                 int64
Price                    int64
City                    object
DeliveryDate    datetime64[ns]
dtype: object

In [65]:
print("Now we are going to check for the negative values in Quantity column")
df[df["Quantity"]==2]

Now we are going to check for the negative values in Quantity column

  CustomerName  OrderDate ProductName  Quantity  Price     City DeliveryDate
1  Priya patel 2023-01-01       Mouse         2     25    Delhi   2023-01-03
6  Sneha reddy 2023-01-04  Headphones         2    150  Kolkata   2023-01-07

In [66]:
df["Quantity"]=df["Quantity"].abs() # converting the negative value to positive
df

,CustomerName,OrderDate,ProductName,Quantity,Price,City,DeliveryDate
0,Rahul sharma,2023-01-01,Laptop,1,1200,Goa,2023-01-05
1,Priya patel,2023-01-01,Mouse,2,25,Delhi,2023-01-03
2,Amit kumar,2023-01-02,Keyboard,1,75,Bangalore,2023-01-06
3,Neha gupta,2023-01-02,Monitor,1,250,Hyderabad,2023-01-07
4,Vikas jain,2023-01-03,Laptop,3,1150,Madras,2023-01-08
5,Priya patel,2023-01-03,Webcam,1,45,Delhi,2023-01-05
6,Sneha reddy,2023-01-04,Headphones,2,150,Kolkata,2023-01-07
7,Rahul sharma,2023-01-04,Mouse,1,20,Goa,2023-01-06
8,Pooja mehta,2023-01-05,Keyboard,1,80,Pune,2023-01-09