In [ ]:
import pandas as pd
import numpy as np

In [ ]:
s=pd.Series([8,9,7,6,5],index=["Lko","vadodara","delhi","mumbai","kolkata"],name="City")
print(s)

Lko         8
vadodara    9
delhi       7
mumbai      6
kolkata     5
Name: City, dtype: int64

In [ ]:
print(s.name)
print(s.index)
print(s.values)
print(s.dtype)

City
Index(['Lko', 'vadodara', 'delhi', 'mumbai', 'kolkata'], dtype='object')
[8 9 7 6 5]
int64

In [ ]:
print(s.iloc[0])
print(s.loc["delhi"])

8
7

In [ ]:
s2=pd.Series([10,20,30,40],index=[1,2,3,4],name="Numbers")
print(s2[2])

20

In [ ]:
s4=pd.Series([10,20,30],index=['a','b','c'])
print(id(s4))
sdrop=s4.drop('b')
print(sdrop)
print(s4)

132668969210160
a    10
c    30
dtype: int64
a    10
b    20
c    30
dtype: int64

VECTORIZATION

In [ ]:
import time
arr=np.arange(1000000)
start=time.time()
total=0
total=np.sum(arr)
print("Time taken by the numpy array is",time.time()-start)

Time taken by the numpy array is 0.0014085769653320312

In [ ]:
import time
l=list(range(1000000))
start=time.time()
total=0
for i in l:
    total=total+i
print("Time taken by the list is",time.time()-start)

Time taken by the list is 0.11499524116516113

PANDAS

In [ ]:
df={"name":["Alice","Bob","Charlie","David","rohit","agasthya","amar","joy"],
    "age":[25,30,35,40,50,21,43,45],
    "city":["New York","Los Angeles","Chicago","Houston","hongkong","delhi","mumbai","kolkata"],
    "sal":[50000,60000,70000,80000,30000,32000,45000,870000]
    }
df=pd.DataFrame(df)
df

       name  age         city     sal
0     Alice   25     New York   50000
1       Bob   30  Los Angeles   60000
2   Charlie   35      Chicago   70000
3     David   40      Houston   80000
4     rohit   50     hongkong   30000
5  agasthya   21        delhi   32000
6      amar   43       mumbai   45000
7       joy   45      kolkata  870000

In [ ]:
df.head(2)

    name  age         city    sal
0  Alice   25     New York  50000
1    Bob   30  Los Angeles  60000

In [ ]:
df.tail(2)

      name  age     city    sal
2  Charlie   35  Chicago  70000
3    David   40  Houston  80000

In [ ]:
for i in range(len(df)):
  df.loc[i,"sal"]=df.loc[i,"sal"]*1.0
df

      name  age         city    sal
0    Alice   25     New York  50000
1      Bob   30  Los Angeles  60000
2  Charlie   35      Chicago  70000
3    David   40      Houston  80000

In [ ]:
df["sal"]=df["sal"].astype(float)
df

      name  age         city      sal
0    Alice   25     New York  50000.0
1      Bob   30  Los Angeles  60000.0
2  Charlie   35      Chicago  70000.0
3    David   40      Houston  80000.0

In [ ]:
df.loc[df["age"]>30,"sal"]*=2
df

       name  age         city      sal
0     Alice   25     New York    50000
1       Bob   30  Los Angeles    60000
2   Charlie   35      Chicago   140000
3     David   40      Houston   160000
4     rohit   50     hongkong    60000
5  agasthya   21        delhi    32000
6      amar   43       mumbai    90000
7       joy   45      kolkata  1740000

In [ ]:
df.loc[df["sal"]>50000,"age"]-=5
df

       name  age         city      sal
0     Alice   20     New York    50000
1       Bob   20  Los Angeles    60000
2   Charlie   25      Chicago   140000
3     David   30      Houston   160000
4     rohit   40     hongkong    60000
5  agasthya   16        delhi    32000
6      amar   33       mumbai    90000
7       joy   35      kolkata  1740000

In [ ]:
data={
    "players":["virat","rohit","sehwag","dhoni","virat","rohit","sehwag","dhoni"],
    "matches":[100,200,300,400,100,200,300,400],
    "runs":[154,200,123,257,309,198,171,120],
    "balls":[50,100,120,120,150,80,120,100]
}
ipl=pd.DataFrame(data)
ipl

  players  matches  runs  balls
0   virat      100   154     50
1   rohit      200   200    100
2  sehwag      300   123    120
3   dhoni      400   257    120
4   virat      100   309    150
5   rohit      200   198     80
6  sehwag      300   171    120
7   dhoni      400   120    100

In [ ]:
ipl["strike_rate"]=(ipl["runs"]/ipl["balls"])*100
ipl

  players  matches  runs  balls  strike_rate
0   virat      100   154     50   308.000000
1   rohit      200   200    100   200.000000
2  sehwag      300   123    120   102.500000
3   dhoni      400   257    120   214.166667
4   virat      100   309    150   206.000000
5   rohit      200   198     80   247.500000
6  sehwag      300   171    120   142.500000
7   dhoni      400   120    100   120.000000

In [ ]:
ipl=ipl.loc[(ipl["players"]=="virat")&(ipl["runs"]>150)]
ipl

  players  matches  runs  balls  strike_rate
0   virat      100   154     50        308.0
4   virat      100   309    150        206.0

It seems that the `ipl` DataFrame was filtered in the previous step, which is why the aggregation only shows data for 'virat'. To get information for all players, I will re-create the `ipl` DataFrame from the original `data` and then recalculate the strike rate.

In [ ]:
data={
    "players":["virat","rohit","sehwag","dhoni","virat","rohit","sehwag","dhoni"],
    "matches":[100,200,300,400,100,200,300,400],
    "runs":[154,200,123,257,309,198,171,120],
    "balls":[50,100,120,120,150,80,120,100]
}
ipl=pd.DataFrame(data)
ipl["strike_rate"]=(ipl["runs"]/ipl["balls"])*100
ipl

  players  matches  runs  balls  strike_rate
0   virat      100   154     50   308.000000
1   rohit      200   200    100   200.000000
2  sehwag      300   123    120   102.500000
3   dhoni      400   257    120   214.166667
4   virat      100   309    150   206.000000
5   rohit      200   198     80   247.500000
6  sehwag      300   171    120   142.500000
7   dhoni      400   120    100   120.000000

Now that the `ipl` DataFrame contains all players, I will re-run the aggregation to get the summary for all of them.

In [ ]:
summ=ipl.groupby("players").agg(
    total_runs=("runs","sum"),
    average_runs=("runs","mean"),
    matches_played=("matches","count"), # Changed to count as sum might not be appropriate for matches
    highest_runs=("runs","max"),
    lowest_runs=("runs","min"),
    total_balls=("balls","sum")
).reset_index()
summ

,players,total_runs,average_runs,matches_played,highest_runs,lowest_runs,total_balls
0,dhoni,377,188.5,2,257,120,220
1,rohit,398,199.0,2,200,198,180
2,sehwag,294,147.0,2,171,123,240
3,virat,463,231.5,2,309,154,200

In [ ]:
players=["virat","rohit","sehwag","dhoni","virat","rohit","sehwag","dhoni"]
runs=[154,200,123,257,309,198,171,120]
total={}
highest={}
for i in range(len(players)):
  player=players[i]
  run=runs[i]
  if player in total:
    total[player]=total[player]+run
  else:
    total[player]=run
  if player in highest:
    if highest[player]<run:
      highest[player]=run
  else:
    highest[player]=run
for player in total:
  print(f"{player}| {total[player]}| {highest[player]}")

virat| 463| 309
rohit| 398| 200
sehwag| 294| 171
dhoni| 377| 257

AGGREGATION

In [ ]:
summ=ipl.groupby("players").agg(
    total_runs=("runs","sum"),
    average_runs=("runs","mean"),
    matches_played=("matches","sum"),
    highest_runs=("runs","max"),
    lowest_runs=("runs","min"),
    total_balls=("balls","sum")
).reset_index()
summ

,players,total_runs,average_runs,matches_played,highest_runs,lowest_runs,total_balls
0,virat,463,231.5,200,309,154,200

#Pandas in Python(28-05-2026)

In [2]:
import pandas as pd
import numpy as np

In [3]:
df={
    "name":["Rahul","Joy","Kumar","Mahi","Jhanvi","Shubham","Priya","Anit"],
    "age":[25,30,35,40,50,21,43,45],
    "city":["New York","Los Angeles","Chicago","Houston","hongkong","delhi","mumbai","kolkata"],
    "sal":[50000,60000,70000,80000,30000,32000,45000,870000],
    "Experience":[2,5,7,10,15,1,8,20],
    "Dept":["IT","HR","Finance","IT","HR","Finance","IT","HR"]
    }
df=pd.DataFrame(df)
df

      name  age         city     sal  Experience     Dept
0    Rahul   25     New York   50000           2       IT
1      Joy   30  Los Angeles   60000           5       HR
2    Kumar   35      Chicago   70000           7  Finance
3     Mahi   40      Houston   80000          10       IT
4   Jhanvi   50     hongkong   30000          15       HR
5  Shubham   21        delhi   32000           1  Finance
6    Priya   43       mumbai   45000           8       IT
7     Anit   45      kolkata  870000          20       HR

In [4]:
salary=df["sal"]
salary

0     50000
1     60000
2     70000
3     80000
4     30000
5     32000
6     45000
7    870000
Name: sal, dtype: int64

In [5]:
dept=df["age"]
dept.values

array([25, 30, 35, 40, 50, 21, 43, 45])

In [6]:
df.age

0    25
1    30
2    35
3    40
4    50
5    21
6    43
7    45
Name: age, dtype: int64

In [9]:
df[["name","Dept","sal","age"]]

      name     Dept     sal  age
0    Rahul       IT   50000   25
1      Joy       HR   60000   30
2    Kumar  Finance   70000   35
3     Mahi       IT   80000   40
4   Jhanvi       HR   30000   50
5  Shubham  Finance   32000   21
6    Priya       IT   45000   43
7     Anit       HR  870000   45

In [12]:
print(type(df["name"])) #series refer to the single column
print(type(df[["name"]])) #Dataframe refers to multiple columns

<class 'pandas.core.series.Series'>
<class 'pandas.core.frame.DataFrame'>

In [16]:
df.loc[:,["name","sal"]]#This will return Dataframe
#this also a column access

      name     sal
0    Rahul   50000
1      Joy   60000
2    Kumar   70000
3     Mahi   80000
4   Jhanvi   30000
5  Shubham   32000
6    Priya   45000
7     Anit  870000

In [18]:
df.iloc[:,2]
df.iloc[:,[1,5]]#This will return column 1 and 5

   age     Dept
0   25       IT
1   30       HR
2   35  Finance
3   40       IT
4   50       HR
5   21  Finance
6   43       IT
7   45       HR

Accessing rows using iloc

In [22]:
print(df.iloc[0:4])

    name  age         city    sal  Experience     Dept
0  Rahul   25     New York  50000           2       IT
1    Joy   30  Los Angeles  60000           5       HR
2  Kumar   35      Chicago  70000           7  Finance
3   Mahi   40      Houston  80000          10       IT

In [25]:
print(df.iloc[[0,2,5]])

      name  age      city    sal  Experience     Dept
0    Rahul   25  New York  50000           2       IT
2    Kumar   35   Chicago  70000           7  Finance
5  Shubham   21     delhi  32000           1  Finance

In [26]:
df.iloc[0:3,0:4]

    name  age         city    sal
0  Rahul   25     New York  50000
1    Joy   30  Los Angeles  60000
2  Kumar   35      Chicago  70000

In [29]:
df.iloc[0:2,[0,3]]

    name    sal
0  Rahul  50000
1    Joy  60000

We are Going to Use .loc function to get the rows printed

In [31]:
df.loc[0:3]

    name  age         city    sal  Experience     Dept
0  Rahul   25     New York  50000           2       IT
1    Joy   30  Los Angeles  60000           5       HR
2  Kumar   35      Chicago  70000           7  Finance
3   Mahi   40      Houston  80000          10       IT

In [32]:
df.loc[[0,2,5]]

      name  age      city    sal  Experience     Dept
0    Rahul   25  New York  50000           2       IT
2    Kumar   35   Chicago  70000           7  Finance
5  Shubham   21     delhi  32000           1  Finance

In [33]:
df2=df.set_index("name")#not applicable
df2

         age         city     sal  Experience     Dept
name
Rahul     25     New York   50000           2       IT
Joy       30  Los Angeles   60000           5       HR
Kumar     35      Chicago   70000           7  Finance
Mahi      40      Houston   80000          10       IT
Jhanvi    50     hongkong   30000          15       HR
Shubham   21        delhi   32000           1  Finance
Priya     43       mumbai   45000           8       IT
Anit      45      kolkata  870000          20       HR

In [35]:
df2.loc[["Jhanvi","Priya"]]

        age      city    sal  Experience Dept
name
Jhanvi   50  hongkong  30000          15   HR
Priya    43    mumbai  45000           8   IT

Using .loc function to print both rows and columns

In [41]:
df.loc[1,"sal"]# accessing specific row and specific column
#multiple rows and single col
df.loc[0:3,"name"]
#single row and multiple col
df.loc[0,["name","age","sal"]]

df.loc[df["age"]>25,["name","sal","age","Dept"]] #using conditions

     name     sal  age     Dept
1     Joy   60000   30       HR
2   Kumar   70000   35  Finance
3    Mahi   80000   40       IT
4  Jhanvi   30000   50       HR
6   Priya   45000   43       IT
7    Anit  870000   45       HR

In [42]:
mask=df["age"]>25 #masking
df.loc[mask,["name","sal","age","Dept"]]

     name     sal  age     Dept
1     Joy   60000   30       HR
2   Kumar   70000   35  Finance
3    Mahi   80000   40       IT
4  Jhanvi   30000   50       HR
6   Priya   45000   43       IT
7    Anit  870000   45       HR

In [44]:
df.loc[(df["age"]>25)&(df["sal"]>50000),["name","sal","age","Dept"]]

    name     sal  age     Dept
1    Joy   60000   30       HR
2  Kumar   70000   35  Finance
3   Mahi   80000   40       IT
7   Anit  870000   45       HR

Query Method like sql

In [46]:
df.query("age>25 and sal>50000 and Dept=='IT'")

   name  age     city    sal  Experience Dept
3  Mahi   40  Houston  80000          10   IT

In [47]:
df.query("age>25 and sal>30000 and city in ['Chicago','mumbai']")

    name  age     city    sal  Experience     Dept
2  Kumar   35  Chicago  70000           7  Finance
6  Priya   43   mumbai  45000           8       IT

@var way to write query

In [48]:
con=30 #using variable
df.query("age>@con and sal>30000 and city in ['Chicago','mumbai']")

    name  age     city    sal  Experience     Dept
2  Kumar   35  Chicago  70000           7  Finance
6  Priya   43   mumbai  45000           8       IT

isin() method (membership method)

In [49]:
df[df["city"].isin(["delhi","mumbai"])]

      name  age    city    sal  Experience     Dept
5  Shubham   21   delhi  32000           1  Finance
6    Priya   43  mumbai  45000           8       IT

In [50]:
df[df["Dept"].isin(["Finance","IT"])]

      name  age      city    sal  Experience     Dept
0    Rahul   25  New York  50000           2       IT
2    Kumar   35   Chicago  70000           7  Finance
3     Mahi   40   Houston  80000          10       IT
5  Shubham   21     delhi  32000           1  Finance
6    Priya   43    mumbai  45000           8       IT

between()-Range Checking

In [51]:
df[df["age"].between(30,40)]

    name  age         city    sal  Experience     Dept
1    Joy   30  Los Angeles  60000           5       HR
2  Kumar   35      Chicago  70000           7  Finance
3   Mahi   40      Houston  80000          10       IT

In [53]:
df[["name","sal"]]

      name     sal
0    Rahul   50000
1      Joy   60000
2    Kumar   70000
3     Mahi   80000
4   Jhanvi   30000
5  Shubham   32000
6    Priya   45000
7     Anit  870000

In [54]:
df[df["age"]>40]

     name  age      city     sal  Experience Dept
4  Jhanvi   50  hongkong   30000          15   HR
6   Priya   43    mumbai   45000           8   IT
7    Anit   45   kolkata  870000          20   HR

In [57]:
df.iloc[2:5]

     name  age      city    sal  Experience     Dept
2   Kumar   35   Chicago  70000           7  Finance
3    Mahi   40   Houston  80000          10       IT
4  Jhanvi   50  hongkong  30000          15       HR

In [59]:
df.loc[0:3,["name","Dept"]]

    name     Dept
0  Rahul       IT
1    Joy       HR
2  Kumar  Finance
3   Mahi       IT

In [60]:
df[df["Dept"]=="IT"]["name"]

0    Rahul
3     Mahi
6    Priya
Name: name, dtype: object

In [65]:
df.iloc[-3:,0:2]

      name  age
5  Shubham   21
6    Priya   43
7     Anit   45

In [66]:
df[df["sal"].between(60000,80000)][["name","city"]]

    name         city
1    Joy  Los Angeles
2  Kumar      Chicago
3   Mahi      Houston

Gropby()

In [67]:
df.groupby("city")['sal'].mean()

city
Chicago         70000.0
Houston         80000.0
Los Angeles     60000.0
New York        50000.0
delhi           32000.0
hongkong        30000.0
kolkata        870000.0
mumbai          45000.0
Name: sal, dtype: float64

In [68]:
df.groupby("Dept")["sal"].agg(['min','max','mean','sum','count'])

           min     max           mean     sum  count
Dept
Finance  32000   70000   51000.000000  102000      2
HR       30000  870000  320000.000000  960000      3
IT       45000   80000   58333.333333  175000      3

In [69]:
df.agg({'age':['min','max','mean'],
        'sal':['min','max','std'],
        'Experience':['min','max','median']})

           age            sal  Experience
min     21.000   30000.000000         1.0
max     50.000  870000.000000        20.0
mean    36.125            NaN         NaN
std        NaN  289575.520621         NaN
median     NaN            NaN         7.5

Sorting + EDA(Exploratory Data Analysis)

In [70]:
df.sort_values("age")

      name  age         city     sal  Experience     Dept
5  Shubham   21        delhi   32000           1  Finance
0    Rahul   25     New York   50000           2       IT
1      Joy   30  Los Angeles   60000           5       HR
2    Kumar   35      Chicago   70000           7  Finance
3     Mahi   40      Houston   80000          10       IT
6    Priya   43       mumbai   45000           8       IT
7     Anit   45      kolkata  870000          20       HR
4   Jhanvi   50     hongkong   30000          15       HR

In [71]:
df.sort_values("Experience",ascending=False)

      name  age         city     sal  Experience     Dept
7     Anit   45      kolkata  870000          20       HR
4   Jhanvi   50     hongkong   30000          15       HR
3     Mahi   40      Houston   80000          10       IT
6    Priya   43       mumbai   45000           8       IT
2    Kumar   35      Chicago   70000           7  Finance
1      Joy   30  Los Angeles   60000           5       HR
0    Rahul   25     New York   50000           2       IT
5  Shubham   21        delhi   32000           1  Finance

In [72]:
df.sort_values("name",ascending=False)

      name  age         city     sal  Experience     Dept
5  Shubham   21        delhi   32000           1  Finance
0    Rahul   25     New York   50000           2       IT
6    Priya   43       mumbai   45000           8       IT
3     Mahi   40      Houston   80000          10       IT
2    Kumar   35      Chicago   70000           7  Finance
1      Joy   30  Los Angeles   60000           5       HR
4   Jhanvi   50     hongkong   30000          15       HR
7     Anit   45      kolkata  870000          20       HR

In [73]:
df.sort_values(["Dept","sal"])

      name  age         city     sal  Experience     Dept
5  Shubham   21        delhi   32000           1  Finance
2    Kumar   35      Chicago   70000           7  Finance
4   Jhanvi   50     hongkong   30000          15       HR
1      Joy   30  Los Angeles   60000           5       HR
7     Anit   45      kolkata  870000          20       HR
6    Priya   43       mumbai   45000           8       IT
0    Rahul   25     New York   50000           2       IT
3     Mahi   40      Houston   80000          10       IT

In [78]:
df['sal_rank']=df['sal'].rank()
df

      name  age         city     sal  Experience     Dept  sal_rank
0    Rahul   25     New York   50000           2       IT       4.0
1      Joy   30  Los Angeles   60000           5       HR       5.0
2    Kumar   35      Chicago   70000           7  Finance       6.0
3     Mahi   40      Houston   80000          10       IT       7.0
4   Jhanvi   50     hongkong   30000          15       HR       1.0
5  Shubham   21        delhi   32000           1  Finance       2.0
6    Priya   43       mumbai   45000           8       IT       3.0
7     Anit   45      kolkata  870000          20       HR       8.0

##EDA - its the process to understand the data wihtout assumptions
###Responsibilty of Analyst is to:
1.understand the data
2.find the pattern

In [80]:
df.head() #shows first 5 rows of data
df.tail() #shows last 5 rows of the data

df.sample(5) #shows random 5 rows of data
df.sample(frac=0.5) #show 50% of random data

     name  age         city    sal  Experience Dept  sal_rank
1     Joy   30  Los Angeles  60000           5   HR       5.0
0   Rahul   25     New York  50000           2   IT       4.0
6   Priya   43       mumbai  45000           8   IT       3.0
4  Jhanvi   50     hongkong  30000          15   HR       1.0

In [82]:
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   name        8 non-null      object
 1   age         8 non-null      int64
 2   city        8 non-null      object
 3   sal         8 non-null      int64
 4   Experience  8 non-null      int64
 5   Dept        8 non-null      object
 6   sal_rank    8 non-null      float64
dtypes: float64(1), int64(3), object(3)
memory usage: 580.0+ bytes

In [84]:
type(df.dtypes)

pandas.core.series.Series

In [89]:
num_cols=df.select_dtypes(include=['int64','float64']).columns
num_cols
cat_col=df.select_dtypes(include=['object']).columns
print("Numerical columns:",len(list(num_cols)),"Categorical columns:",len(list(cat_col)))

Numerical columns: 4 Categorical columns: 3

##changing datatype

In [92]:
df['age']=df['age']*1.0
df['age']=df['age'].astype(float)
df

      name   age         city     sal  Experience     Dept  sal_rank
0    Rahul  25.0     New York   50000           2       IT       4.0
1      Joy  30.0  Los Angeles   60000           5       HR       5.0
2    Kumar  35.0      Chicago   70000           7  Finance       6.0
3     Mahi  40.0      Houston   80000          10       IT       7.0
4   Jhanvi  50.0     hongkong   30000          15       HR       1.0
5  Shubham  21.0        delhi   32000           1  Finance       2.0
6    Priya  43.0       mumbai   45000           8       IT       3.0
7     Anit  45.0      kolkata  870000          20       HR       8.0

In [96]:
df.describe()
df.describe(include="object")

         name      city Dept
count       8         8    8
unique      8         8    3
top     Rahul  New York   IT
freq        1         1    3

In [94]:
df['sal'].agg(['min','max','mean','std'])

min      30000.000000
max     870000.000000
mean    154625.000000
std     289575.520621
Name: sal, dtype: float64

In [95]:
df['Experience'].kurt()

np.float64(-0.02889892984542275)

In [97]:
df.describe(include="all")

         name        age      city            sal  Experience Dept  sal_rank
count       8   8.000000         8       8.000000    8.000000    8   8.00000
unique      8        NaN         8            NaN         NaN    3       NaN
top     Rahul        NaN  New York            NaN         NaN   IT       NaN
freq        1        NaN         1            NaN         NaN    3       NaN
mean      NaN  36.125000       NaN  154625.000000    8.500000  NaN   4.50000
std       NaN  10.176128       NaN  289575.520621    6.436503  NaN   2.44949
min       NaN  21.000000       NaN   30000.000000    1.000000  NaN   1.00000
25%       NaN  28.750000       NaN   41750.000000    4.250000  NaN   2.75000
50%       NaN  37.500000       NaN   55000.000000    7.500000  NaN   4.50000
75%       NaN  43.500000       NaN   72500.000000   11.250000  NaN   6.25000
max       NaN  50.000000       NaN  870000.000000   20.000000  NaN   8.00000

In [98]:
city_count=df['city'].value_counts()
city_count

city
New York       1
Los Angeles    1
Chicago        1
Houston        1
hongkong       1
delhi          1
mumbai         1
kolkata        1
Name: count, dtype: int64

In [100]:
print(df['city'].value_counts(normalize=True)*100)
print(df['city'].value_counts)

city
New York       12.5
Los Angeles    12.5
Chicago        12.5
Houston        12.5
hongkong       12.5
delhi          12.5
mumbai         12.5
kolkata        12.5
Name: proportion, dtype: float64
<bound method IndexOpsMixin.value_counts of 0       New York
1    Los Angeles
2        Chicago
3        Houston
4       hongkong
5          delhi
6         mumbai
7        kolkata
Name: city, dtype: object>